<?php

if (!defined('ABSPATH')) {
    exit;
}

/**
 * "Search" settings screen (submenu of the WR Ajax Load More menu).
 *
 * Replaces the old auto-collected ACF field cache in WRALM_Search_ACF: the
 * admin now picks explicitly which ACF fields the front-end search should look
 * inside, and can cap how expensive a search query gets. Everything is one
 * option; WRALM_Search_ACF reads it through WRALM_Search_Settings::get().
 */
class WRALM_Search_Settings
{
    const OPTION_NAME  = 'wralm_search_settings';
    const OPTION_GROUP = 'wralm_search';
    const PAGE_SLUG    = 'wralm-search';

    /** @var \WRALM\UiKit\SettingsPage|null */
    private $page = null;

    public function __construct()
    {
        add_action('admin_menu', [$this, 'add_page']);
        add_action('admin_init', [$this, 'register']);
    }

    /**
     * Normalised settings with defaults applied. Safe to call anywhere.
     *
     * @return array{
     *     acf_fields: string[],
     *     search_comments: bool,
     *     search_terms: bool,
     *     max_words: int,
     *     min_word_length: int
     * }
     */
    public static function get()
    {
        $raw = get_option(self::OPTION_NAME, []);
        if (!is_array($raw)) {
            $raw = [];
        }

        $acf_fields = isset($raw['acf_fields']) && is_array($raw['acf_fields'])
            ? array_values(array_unique(array_filter(array_map('sanitize_key', $raw['acf_fields']))))
            : [];

        return [
            'acf_fields'      => $acf_fields,
            'search_comments' => !isset($raw['search_comments']) || (bool) $raw['search_comments'],
            'search_terms'    => !isset($raw['search_terms']) || (bool) $raw['search_terms'],
            'max_words'       => isset($raw['max_words']) ? max(1, min(20, (int) $raw['max_words'])) : 6,
            'min_word_length' => isset($raw['min_word_length']) ? max(1, min(10, (int) $raw['min_word_length'])) : 3,
        ];
    }

    /**
     * Every ACF field name available across public post types, as
     * `name => "Label (name)"`. Top-level fields only — nested repeater / group
     * sub-fields are stored under composite meta keys and are out of scope.
     *
     * @return array<string,string>
     */
    public static function available_acf_fields()
    {
        if (!function_exists('acf_get_field_groups') || !function_exists('acf_get_fields')) {
            return [];
        }

        $out = [];
        foreach (get_post_types(['public' => true], 'names') as $post_type) {
            $groups = acf_get_field_groups(['post_type' => $post_type]);
            if (empty($groups)) {
                continue;
            }
            foreach ($groups as $group) {
                $fields = acf_get_fields($group['key']);
                if (empty($fields)) {
                    continue;
                }
                foreach ($fields as $field) {
                    if (empty($field['name'])) {
                        continue;
                    }
                    $name = sanitize_key($field['name']);
                    $label = !empty($field['label']) ? $field['label'] : $name;
                    $out[$name] = $label . ' (' . $name . ')';
                }
            }
        }

        ksort($out);
        return $out;
    }

    public function add_page()
    {
        add_submenu_page(
            'wr-ajax-load-more',
            __('Search Settings', 'wr-ajax-load-more-and-filters'),
            __('Search', 'wr-ajax-load-more-and-filters'),
            'manage_options',
            self::PAGE_SLUG,
            [$this, 'render']
        );
    }

    public function register()
    {
        $this->page()->register();
    }

    public function render()
    {
        $this->page()->render();
    }

    /**
     * The screen is the ui-kit SettingsPage (inc/ui-kit/, generated by the
     * frontend build) rendered by the SettingsForm component; saving stays the
     * Settings API round trip. All fields live in one array option, so the
     * first field carries the option's sanitize callback.
     */
    private function page(): \WRALM\UiKit\SettingsPage
    {
        if ($this->page !== null) {
            return $this->page;
        }

        $option = self::OPTION_NAME;
        $section = 'wralm_search_main';
        $available = self::available_acf_fields();
        $description = esc_html__(
            'Controls what the [all_posts_ajax] search looks inside. Post title and content are always searched.',
            'wr-ajax-load-more-and-filters'
        );
        $fields = [];

        if (empty($available)) {
            $description .= ' ' . esc_html__('No ACF fields detected (Advanced Custom Fields not active, or no field groups on public post types).', 'wr-ajax-load-more-and-filters');
        } else {
            $fields[] = [
                'id' => $option,
                'key' => 'acf_fields',
                'type' => 'select',
                'multiple' => true,
                'options' => $available,
                'label' => __('ACF fields to search', 'wr-ajax-load-more-and-filters'),
                'desc' => __('Nothing selected = the search does not touch ACF values at all (fastest).', 'wr-ajax-load-more-and-filters'),
                'section' => $section,
            ];
        }

        $fields[] = [
            'id' => $option,
            'key' => 'search_comments',
            'type' => 'checkbox',
            'label' => __('Also search comment text', 'wr-ajax-load-more-and-filters'),
            'section' => $section,
        ];
        $fields[] = [
            'id' => $option,
            'key' => 'search_terms',
            'type' => 'checkbox',
            'label' => __('Also search taxonomy term names', 'wr-ajax-load-more-and-filters'),
            'section' => $section,
        ];
        $fields[] = [
            'id' => $option,
            'key' => 'max_words',
            'type' => 'number',
            'min' => 1,
            'max' => 20,
            'label' => __('Max words per search', 'wr-ajax-load-more-and-filters'),
            'section' => $section,
        ];
        $fields[] = [
            'id' => $option,
            'key' => 'min_word_length',
            'type' => 'number',
            'min' => 1,
            'max' => 10,
            'label' => __('Ignore words shorter than (characters)', 'wr-ajax-load-more-and-filters'),
            'section' => $section,
        ];
        $fields[0]['sanitize_callback'] = [$this, 'sanitize'];

        $this->page = new \WRALM\UiKit\SettingsPage([
            'page' => self::PAGE_SLUG,
            'group' => self::OPTION_GROUP,
            'sections' => [
                $section => [
                    'title' => __('Front-end search', 'wr-ajax-load-more-and-filters'),
                    'description' => $description,
                ],
            ],
            'fields' => $fields,
            'show_errors' => true,
            // Values come normalised, with defaults, from get().
            'value' => function (array $field) {
                return self::get()[$field['key']];
            },
            'strings' => [
                'submit' => __('Save Changes', 'wr-ajax-load-more-and-filters'),
                'no_js' => __('This page needs JavaScript.', 'wr-ajax-load-more-and-filters'),
            ],
        ]);

        return $this->page;
    }

    public function sanitize($input)
    {
        if (!is_array($input)) {
            $input = [];
        }

        $available = array_keys(self::available_acf_fields());
        $picked = isset($input['acf_fields']) && is_array($input['acf_fields'])
            ? array_map('sanitize_key', $input['acf_fields'])
            : [];

        return [
            'acf_fields'      => array_values(array_intersect($picked, $available)),
            'search_comments' => !empty($input['search_comments']),
            'search_terms'    => !empty($input['search_terms']),
            'max_words'       => isset($input['max_words']) ? max(1, min(20, (int) $input['max_words'])) : 6,
            'min_word_length' => isset($input['min_word_length']) ? max(1, min(10, (int) $input['min_word_length'])) : 3,
        ];
    }

}
